version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_meu_port
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: menssagens
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    container_name: backend_meu_port
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    env_file:
      - .env

  frontend:
    image: nginx:alpine
    container_name: frontend_meu_port
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "80:80"

volumes:
  mysql_data:
